[2023-03-11 20:50:05] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-03-11 20:50:05] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-03-11 20:50:05] [INFO    ] discord.client: logging in using static token
[2023-03-11 20:50:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 72e25720c30ddf7a122af5f95df8a1be).
[2023-03-11 20:50:07] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/main.py", line 24, in on_ready
    log("INFO", f"Logged in as {bot.user}")
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/utils.py", line 173, in log
    with open(f"{DATA_DIR}/bot.log", 'a') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/src/data/bot.log'
[2023-03-11 20:52:50] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-03-11 20:52:50] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-03-11 20:52:50] [INFO    ] discord.client: logging in using static token
[2023-03-11 20:52:51] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 524d6ac4b636141440e4fb51ad41e549).
[2023-03-11 20:52:53] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/main.py", line 24, in on_ready
    log("INFO", f"Logged in as {bot.user}")
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/utils.py", line 173, in log
    with open(f"{DATA_DIR}/bot.log", 'a') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/src/data/bot.log'
[2023-03-11 20:53:12] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-03-11 20:53:12] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-03-11 20:53:12] [INFO    ] discord.client: logging in using static token
[2023-03-11 20:53:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a4cc3914b5bdb07a51b7c0342dd64b2f).
[2023-03-11 20:53:15] [INFO    ] Logged in as yasname#7557
[2023-03-11 20:53:15] [INFO    ] cmds.stuff.embed loaded 
[2023-03-11 20:53:15] [INFO    ] cmds.stuff.owner loaded 
[2023-03-11 20:53:15] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 934, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/cmds/stuff/apps.py", line 6, in <module>
    from src.utils import GetLogLink, log, get_data
ModuleNotFoundError: No module named 'src'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/Users/robin/Library/Mobile Documents/com~apple~CloudDocs/Code/sinfbot/src/main.py", line 26, in on_ready
    await bot.load_extension(ext)
  File "/opt/homebrew/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/opt/homebrew/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 937, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cmds.stuff.apps' raised an error: ModuleNotFoundError: No module named 'src'
[2023-03-11 20:53:41] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-03-11 20:53:41] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-03-11 20:53:41] [INFO    ] discord.client: logging in using static token
[2023-03-11 20:53:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6c1f426671d00816c067d1a89fae777d).
[2023-03-11 20:53:44] [INFO    ] Logged in as yasname#7557
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.embed loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.owner loaded 
[2023-03-11 20:53:44] [INFO    ] adding Avatar to context menu
[2023-03-11 20:53:44] [INFO    ] adding Birthday to context menu
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.apps loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.birthday loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.help loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.tetrio loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.stuff.general loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.cutie.resp loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.cutie.control loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.events.error loaded 
[2023-03-11 20:53:44] [INFO    ] cmds.events.message loaded 
